car:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  wheel_lf_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_lf_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  wheel_lb_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_lb_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  wheel_rf_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_rf_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  wheel_rb_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_rb_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  gimbal_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: gimbal_yaw_hoint
    pid: {p: 100.0, i: 0.0, d: 0.0}
  gimbal_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: gimbal_pitch_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}

    
